# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rhombus < Formula
  desc "CLI for the Rhombus API"
  homepage "https://github.com/RhombusSystems/rhombus-cli"
  version "0.13.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RhombusSystems/rhombus-cli/releases/download/v0.13.2/rhombus-cli_0.13.2_darwin_amd64.tar.gz"
      sha256 "5c4451b7fbb0bc5ac0716a8bfe68ac2f5b63acfe67fd4244af3d40940d92b996"

      define_method(:install) do
        bin.install "rhombus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RhombusSystems/rhombus-cli/releases/download/v0.13.2/rhombus-cli_0.13.2_darwin_arm64.tar.gz"
      sha256 "676b496f0d14e7986f887286549ad2e0ca22528c719f0ed618b77e689982e81b"

      define_method(:install) do
        bin.install "rhombus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RhombusSystems/rhombus-cli/releases/download/v0.13.2/rhombus-cli_0.13.2_linux_amd64.tar.gz"
      sha256 "8b4e6cc5c7ffae2ee3d5afa6d29e6e240aab2072f2623dae3f5111d07f7bbed0"
      define_method(:install) do
        bin.install "rhombus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RhombusSystems/rhombus-cli/releases/download/v0.13.2/rhombus-cli_0.13.2_linux_arm64.tar.gz"
      sha256 "943222b2f2f23aa7ca2f9b928507f6a47ce041681012b42f2b725f60bb73b844"
      define_method(:install) do
        bin.install "rhombus"
      end
    end
  end

  test do
    system "#{bin}/rhombus", "--help"
  end
end
